#spring.datasource.url=jdbc:mariadb://anataarisa.hopto.org:3306/pim
#spring.datasource.username=pim
#spring.datasource.password=Vinh12345.
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.properties.hibernate.format_sql=true
#spring.sql.init.encoding=UTF-8
#spring.jpa.properties.hibernate.generate_statistics=true
#spring.jpa.open-in-view=true
#spring.profiles.active=dev
#
#server.servlet.context-path=/api/v1
#server.port=9090
#server.error.include-message=always
aws:
  access:
    key:
      id: AKIA2EWSF45CBHDRXQJK
  s3:
    region: ap-southeast-1
    bucket:
      name: ademyimage
  secret:
    access:
      key: tN7GXYsy2zZHqb1znrfCf/hmNXzdFuRN9MSPdG2P

spring:
  datasource:
    url: jdbc:mariadb://anataarisa.hopto.org:3306/hitler-store
    username: pim
    password: Vinh12345.
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
    open-in-view: true
  sql:
    init:
      encoding: utf-8
  profiles:
    active: dev
#  session:
#    store-type=jdbc:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username:
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true



  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 509336143279-ng2g9fdpg8pkt1j3jlj24au6l96hk0qn.apps.googleusercontent.com
            client-secret: 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
          facebook:
            client-id: 659086803093851
            client-secret: 9e4114afc12752f6fdb8bd7b99d4bcc4

server:
  servlet:
    context-path: /api/v1
  port: 9090
  error:
    include-message: always


logging:
  level:
    org:
      springframework:
        security: TRACE


paypal:
  mode: sandbox
  client:
    id: AUT1Z0RRsKw1aazKBzzslShE8dfLWWjd4OWpVFeSJWfdFNuwik1k2-2tQ3mD5dk4BM7vP90SnuESyUYK
    secret: EKfpcVNpYEkGOAThX2Tqi5tcq560S1FpOhNSeux_U6tNAaVC8LU-7Y-55J3puelLhfKutNH7tkuPQEMu


frontend:
  url: http://localhost:3000/

#auththentication:
#  facebook-url: /oauth2/authorization/facebook
#  google-url: /oauth2/authorization/google