aws:
  access:
    key:
      id: AKIA2EWSF45CBHDRXQJK
  s3:
    region: ap-southeast-1
    bucket:
      name: ademyimage
  secret:
    access:
      key: tN7GXYsy2zZHqb1znrfCf/hmNXzdFuRN9MSPdG2P

spring:
  datasource:
    #    url: jdbc:mariadb://anataarisa.hopto.org:3306/hitler-store
    #    url: jdbc:mariadb://anataarisa.hopto.org:3306/ademy-test
    url: jdbc:mariadb://anataarisa.hopto.org:3306/ademy
    #    url: jdbc:mariadb://database:3306/ademy
    username: pim
    password: Vinh12345.
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    open-in-view: true
  sql:
    init:
      encoding: utf-8
  #  session:
  #    store-type=jdbc:
  mail:
    host: smtp.gmail.com
    port: 587
    username: no.reply.ademy@gmail.com
    password: ztgzeyizzyicozuc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 509336143279-ng2g9fdpg8pkt1j3jlj24au6l96hk0qn.apps.googleusercontent.com
            client-secret: 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

server:
  servlet:
    context-path: /api/v1
  port: 9090
  error:
    include-message: always


logging:
  level:
    org:
      springframework:
        security: TRACE
      hibernate:
        type: trace
        orm:
          jdbc:
            bind: trace



paypal:
  client:
    secret: EHGsrSIQG-aODbOaHmd5YnhCLNS3Zq3x3einniprXjRkABpA-U0UEXy9w_hp-YElLEwsQv6tmQNJ4ZVS
    app: AWbOtZPREQ6DxSCza2yGZT82kQTW9T17r8xezCuKARBoBM5jli0FdOPrdRVkytKLdeaaFaiM6k-tHlr6
  mode: sandbox


frontend:
  url: http://localhost:3000/

api:
  base:
    url: http://localhost:9090/api/v1/

security:
  secret-key: 49906c40c2bd2ce2a35571ebf991e74573d0e5cc5db9e032a7b1c5af42c8b038

#auththentication:
#  facebook-url: /oauth2/authorization/facebook
#  google-url: /oauth2/authorization/google
