version: '3.1'

services:
  marian-database:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USERNAME:
      MYSQL_PASSWORD:
    volumes:
      - data:/var/lib/mysql
  drawing-courses-api:
    build: ./
    restart: always
    depends_on: marian-database
